# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия автора')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250, verbose_name='Название книги')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Author')),
            ],
        ),
    ]
