# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=250, verbose_name='автор комментария')),
                ('comment_text', models.TextField(max_length=250, verbose_name='текст комментария')),
                ('comments_link_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Author')),
                ('comments_link_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=250, verbose_name='фамилия автора')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_link_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.User'),
        ),
    ]
