# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20170421_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments_link_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments_link_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.Book'),
        ),
    ]
