# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date change')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date created')),
                ('title', models.CharField(max_length=250, verbose_name='Name the albumx')),
                ('descr', models.TextField(blank=True, verbose_name='Full description')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date change')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date created')),
                ('alt', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
        ),
    ]
